# Generated by Django 3.2.7 on 2023-03-08 11:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('PMS', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vechile_name', models.CharField(max_length=40)),
                ('vechile_type', models.CharField(choices=[('two wheeler', 'two wheeler'), ('three wheeler', 'three wheeler'), ('Four wheeler', 'Four wheeler')], max_length=30)),
                ('vechile_no', models.CharField(max_length=40)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
