# Generated by Django 3.2.16 on 2023-02-05 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PMS', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='total_rows',
            field=models.IntegerField(default=10),
        ),
    ]
