# Generated by Django 3.2.16 on 2023-03-13 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PMS', '0002_vehicle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PMS.building')),
                ('coloumn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PMS.coloumn')),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PMS.floor')),
                ('row', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PMS.rows')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PMS.vehicle')),
            ],
        ),
    ]
