# Generated by Django 3.2.7 on 2023-02-18 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PMS', '0003_rows'),
    ]

    operations = [
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor_name', models.CharField(max_length=40)),
                ('building_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PMS.building')),
            ],
        ),
    ]
