# Generated by Django 3.2.7 on 2023-02-18 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PMS', '0004_floor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rows',
            name='building_id',
        ),
        migrations.AddField(
            model_name='rows',
            name='floor_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='PMS.floor'),
            preserve_default=False,
        ),
    ]
